<?php
// $Id$
/**
 * @file
 * Module for providing statistic reports on content produced by Education LifeDesks users.
 */
/**
 * Implementation of hook_perm().
 */
function edulifedesks_statistics_perm() {
  return array('access content statistics');
}
/**
 * Implementation of hook_menu().
 */
function edulifedesks_statistics_menu() {
  $items['admin/content/statistics'] = array(
    'title' => 'Content statistics',
    'description' => 'Data on the amount of content and its status.',
    'page callback' => 'edulifedesks_statistics_overview',
    'access arguments' => array('access content statistics'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'edulifedesks_statistics.admin.inc',
    'file path' => drupal_get_path('module', 'edulifedesks_statistics') .'/includes',
  );
  return $items;
}
/**
 * Implementation of hook_views_api().
 */
function edulifedesks_statistics_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'edulifedesks_statistics') .'/includes'
  );
}